Required libraries:
-Numpy

Vdo 11 -Tensors

0-D tensors

In [2]:
import numpy as np
a=np.array(2)
print(a)
# Dimension
print(a.ndim)

2
0


1-D tensors="vector"(dimension of vector=number of terms in 1-d tensor)
only one axis

In [6]:
import numpy as np
a=np.array([1,2,3])
print(a)
#Dimension
print(a.ndim)

[1 2 3]
1


2-D tensors="matrix"(dimension of matrix=m*n because 2 axis column and row)
collection of vectors

In [8]:
import numpy as np
a=np.array([[1,2,3],[3,45,4],[3,45,4]])
print(a)
#Dimension
print(a.ndim)

[[ 1  2  3]
 [ 3 45  4]
 [ 3 45  4]]
2


N-d tensors is a collection of n-1 d tensors and rank=n and axis =n
dimension writing format of n-d tensor= a1*a2*a3.....an

In [9]:
import numpy as np
a=np.array([[[1,2,3],[3,45,4],[3,45,4]],[[1,2,3],[3,45,4],[3,45,4]],[[1,2,3],[3,45,4],[3,45,4]]])
print(a)
#Dimension
print(a.ndim)

[[[ 1  2  3]
  [ 3 45  4]
  [ 3 45  4]]

 [[ 1  2  3]
  [ 3 45  4]
  [ 3 45  4]]

 [[ 1  2  3]
  [ 3 45  4]
  [ 3 45  4]]]
3


Number of Axis=number of dimension=Rank of tensor
shape=dimension format =ro*col*.... if multiple dimesions

1-d: (n,)
2-d: (m,n)

size=evaluation of shape
for(scalar shape=1)

Note:
1-d is collection of 0-d
2-d is collection of 1-d and so on

Although vector=1-d tensor but it has its own dimension that is not the dimension of tensor
Example) Students=1000
cgpa,iq,state is input columns
Let's say two states W.B ,Karnataka, and name them as '0' and '1' -This is called **Label Encoding**


In [ ]:
stu1=[8.1,91,0]
stu2=[9,87,1]
# Here dimension of tensor is one but for vector it is 3 as 3 input columns
# Each entry is a one-d tensor
# [1,0,0,0,1......] it is a collection of the 3rd input column in another 1-d tensor

# 2-D Tensor example
Collection of 1-d tensor like above students collection in a list will be a matrix
It is denoted by **D**

In [2]:
stu1=[8.1,91,0]
stu2=[9,87,1]
D=[stu1,stu2]
D

[[8.1, 91, 0], [9, 87, 1]]

# 3-d Tensors
Example 1)NLP
Let say we provide text to our machine then it can't understand it ,we need to provide it in the form of numbers-This is called **vectorization**
There are many techniques of vectorization

In [18]:
import numpy as np
# Say these are the inputs
text1="Hi Nitish"
text2="Hi Rahul"
text3="Hi Ankit"
# So define a //*corpus*//
corpus=np.eye(4,4) #The four words represented by each row
print(corpus)
# define text

t1=np.array([corpus[0,:],corpus[1,:]])
t2=np.array([corpus[0,:],corpus[2,:]])
t3=np.array([corpus[0,:],corpus[3,:]])
print("text1")
print(t1)
print("text2")
print(t2)
print("text3")
print(t3)
ThreeD=np.array([t1,t2,t3])
ThreeD
# Since 3 2-d tensors in 1 3-d collection, then in each 2-d we have 2 1-d and in each 1-d we have 4 scalars or 0-d
print(ThreeD.shape)
print(ThreeD.size)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
text1
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]
text2
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]]
text3
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]]
(3, 2, 4)
24


Example 2)**Time Series data**- The data is collected after regular intervals of time ex )
Let's say we record higest and lowest prices of one stock in one day for 10 years then we should have 10*365*2 tensor
middle axis=time axis, no of collections of 1-d
first=no of collection of 2-d
last =no of entries in 1-d

# 4-D Tensors
Example) Image Processing and Computer vision
Since Image is matrix of pixels which has a value in each pixel that shows it colors etc
An image is collection of R,G,B matrix so one image is 3-D tensors
Let's say each matrix has 1200*800
then one image will be a 3-D tensor of (3* 1200 * 800)
But if we provide multiple images (say 50) to our model we have (50* 3 * 1200 * 800)

# 5-D Tensors
Example) Each vdo has multiple images but moving with more speed then persistence of vision(12/second)
generally we have 30fps,60 fps etch which means that no of images/frames per second
so let's say we have 10 vdos of 60fps where each vdo is of 40 seconds and resolution is 480*720
then (10* 2400* 3 * 420 * 720) =(vdos*no of images in each vdo *shape of image)
here
(21772800000)=no of scalars , assuming each to be float we will requiure 4* 21772800000 bytes or 4* 2177280000 *8 bits
or 81 gb if we divide by (1024^3) to get gigabytes-
so we doesn't do like this- wwe use codecs like mp4,mkv etc they reduce size

**-----------------------------------------------------------------VDO 12 starts----------------------------------------------------------------------**

#Pandas how to import data set
the file should be in same folder or provide its path

In [21]:
import pandas as pd
df=pd.read_csv('College Data.csv')
df

College ID       Country  Total Students   Male  Female       CGPA  \
0      College 52            UK           27002   2593   11644  10.000000   
1      College 93   Switzerland           11913   9392    2521   6.951278   
2      College 15         Japan           15644   5475    4388   9.327922   
3      College 72     Singapore           13239   7363    5876   8.681112   
4      College 61        Canada           10236  13339   -3103   8.560567   
...           ...           ...             ...    ...     ...        ...   
49995  College 93         India           14676  10771    3905   8.335598   
49996  College 48         Japan           21908  10682    6820   8.490003   
49997  College 67  South Africa           17263  11035    6228   5.979781   
49998  College 54           USA           11371  10233    1138   7.714894   
49999  College 16         China           20867  10643   10224   8.861043   

       Annual Family Income                   Branch      Sports  \
0                   3574250                  Physics    Swimming   
1                    762556     Chemical Engineering   Athletics   
2                   1795845  Business Administration  Volleyball   
3                   1222223                  Physics      Tennis   
4                   1921133            Biotechnology   Athletics   
...                     ...                      ...         ...   
49995               3151197        Civil Engineering     Cricket   
49996               3060006                  Physics       Chess   
49997               1519563     Chemical Engineering   Athletics   
49998               2429788   Mechanical Engineering    Swimming   
49999               3962086  Business Administration      Tennis   

       Research Papers Published  Placement Rate  Faculty Count  
0                             39          100.00            655  
1                             31           68.84            256  
2                             37           91.99            555  
3                             48           97.98            455  
4                             34           83.56            310  
...                          ...             ...            ...  
49995                         20           65.61            596  
49996                          9           99.15            383  
49997                         35           78.28            671  
49998                         11           88.46            164  
49999                         27           84.22            445  

[50000 rows x 12 columns]

now in anaconda